### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by fabaff** [valentinalexeev/pwaqi#1]
The implementation in Home Assistant which is using pwapi is polluting the log file due to exceptions which are not catched.

```bash
16-11-27 22:02:57 ERROR (Thread-4) [homeassistant.components.sensor.waqi] Unable to fetch data from WAQI.
Traceback (most recent call last):
  File "/home/fab/Documents/repos/home-assistant/homeassistant/components/sensor/waqi.py", line 101, in update
    self._data = pwaqi.getStationObservation(self._station_id)
  File "/home/fab/Documents/repos/home-assistant/lib64/python3.5/site-packages/pwaqi/__init__.py", line 49, in getStationObservation
    obsJson = r.json()["rxs"]["obs"][0]["msg"]
KeyError: 'msg'
```

**Comment by valentinalexeev** [comment]
@fabaff can you tell me which station were you trying to check data for? This type of response means that WAQI did find the station you were asking for (otherwise there would be no call to .getStationObservation() from waqi sensor in HA) however WAQI returned nothing to a query for the data of that specific station.

**Comment by fabaff** [comment]
`beijin`
