### ISSUE TITLE
Updates out of sync

### ISSUE THREAD

**Issue by stelgenhof** [valentinalexeev/pwaqi#4]
When using the WAQI component in Home Assistant, I noticed it does perform the updates regularly, however it does not pull the latest WAQI observation for my station (Yokosuka, Japan).

Home Assistant showing the latest observation is from 2017-01-27@18:00:
![waqi_hass](https://cloud.githubusercontent.com/assets/529544/22535303/837a1498-e93d-11e6-99f0-21c64d78e6eb.png)

Using curl to check the latest observation:
![curl_waqi](https://cloud.githubusercontent.com/assets/529544/22535331/b53209d2-e93d-11e6-8758-063e48b790eb.png)
shows the latest observation is from 2017-02-02 11:00:00

**Comment by valentinalexeev** [comment]
Hi! Thanks for reporting this. I had observed this behavior before however I could not pinpoint the exact reason. It seems that WAQI uses some sort of a reverse proxy that may cache older results for a while. For me once it was returning values as old as half a year ago. At the same time the URLs and the headers sent by pwaqi were identical to what browser had sent. Another reason could be that WAQI has some stale data from stations that went offline and new ones opened with the same name. 

Unfortunately their is no public API or support for the service so I had to do a scrapper instead. I can't verify my suspicions. 

For me it seems to work because I was not using exact station names but city / location instead. This way it seems it was pulling the right station data.

**Comment by stelgenhof** [comment]
Thanks for the explanation. Not entirely sure why you need to do some scraping. If I use curl and their API endpoint I successfully can retrieve the station observation data. (I do use my own token by the way).

**Comment by tony2nite** [comment]
I've created a PR that seems to fix the stale results issue.

@stelgenhof with your note on tokens, made me think this library should probably be updated to require a valid token to keep within the terms of service of the [AQI API](http://aqicn.org/api/)

>**API Usage**
> - All the APIs are provided for free.
> - A valid key must be used for accessing the API.
> - All the API are subjected to quota.
> 
>The default quota is max 1000 (one thousand) requests per minute (~16RPS) and with burst up to 60 requests.

**Comment by valentinalexeev** [comment]
Thanks to @tony2nite we now have this issue fixed.
I have bumped component version to 2.0 as the change (introduction of token) breaks the module API.

**Comment by tony2nite** [comment]
Nice one @valentinalexeev. Thanks for jumping on it so quickly.

**Comment by valentinalexeev** [comment]
FYI, here is a corresponding HA PR - home-assistant/home-assistant/pull/5944.

**Comment by tony2nite** [comment]
I see there is still an issue on Home Assistant https://github.com/home-assistant/home-assistant/issues/6244 because my patch still didn't get the URL quite right.

But it also seems @valentinalexeev you have successfully squashed it in pwaqi v3.0.0. I've been using v3 locally with HA and am finally getting good logged data coming through. Maybe another version bump will finally fix it.

<img width="365" alt="screen shot 2017-03-03 at 07 35 49" src="https://cloud.githubusercontent.com/assets/467271/23540839/1431baf6-ffe4-11e6-9499-e018db81005a.png">

**Comment by valentinalexeev** [comment]
@tony2nite yes, I've noticed that as well. For some reason what used to be working did not work in the end.
The 3.0 bump will require some adaptation in HA sensor as the new API endpoint does not return all data as it seems...
